# -*- coding: utf-8 -*-
"""stock_portfolio_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeL0G1BdGcMoEcQYWJcyrwpA9vBIaczt
"""

STOCK_PRICES = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 170,
    "MSFT": 450,
    "AMZN": 190
}


def display_stocks():
    print("\nAvailable Stocks:")
    for stock, price in STOCK_PRICES.items():
        print(f"{stock} : ${price}")


def portfolio_tracker():
    portfolio = {}
    total_value = 0

    print("=" * 45)
    print("      STOCK PORTFOLIO TRACKER")
    print("=" * 45)

    display_stocks()

    while True:
        stock = input("\nEnter Stock Name (or 'done' to finish): ").upper()

        if stock == "DONE":
            break

        if stock not in STOCK_PRICES:
            print("Invalid Stock Name! Try Again.")
            continue

        try:
            quantity = int(input("Enter Quantity: "))
            if quantity <= 0:
                print("Quantity must be greater than 0.")
                continue
        except ValueError:
            print("Please enter a valid number.")
            continue

        value = STOCK_PRICES[stock] * quantity
        portfolio[stock] = portfolio.get(stock, 0) + quantity
        total_value += value

    print("\n" + "=" * 45)
    print("PORTFOLIO SUMMARY")
    print("=" * 45)

    with open("portfolio_summary.txt", "w") as file:
        file.write("STOCK PORTFOLIO SUMMARY\n")
        file.write("=" * 40 + "\n")

        for stock, quantity in portfolio.items():
            price = STOCK_PRICES[stock]
            value = price * quantity

            print(f"{stock} | Qty: {quantity} | Price: ${price} | Value: ${value}")
            file.write(
                f"{stock} | Qty: {quantity} | Price: ${price} | Value: ${value}\n"
            )

        print("-" * 45)
        print(f"Total Investment Value: ${total_value}")

        file.write("-" * 40 + "\n")
        file.write(f"Total Investment Value: ${total_value}\n")

    print("\nPortfolio summary saved as 'portfolio_summary.txt'")


if __name__ == "__main__":
    portfolio_tracker()